[Icon Theme]
Name=Nebula
Comment=NebulaOS Official Squircle Theme
Inherits=Adwaita,hicolor
Directories=scalable/apps,scalable/actions,scalable/categories,scalable/devices,scalable/mimetypes,scalable/places,scalable/status

[scalable/apps]
Size=344
MinSize=16
MaxSize=512
Type=Scalable

[scalable/actions]
Size=344
MinSize=16
MaxSize=512
Type=Scalable

[scalable/categories]
Size=344
MinSize=16
MaxSize=512
Type=Scalable

[scalable/devices]
Size=344
MinSize=16
MaxSize=512
Type=Scalable

[scalable/mimetypes]
Size=344
MinSize=16
MaxSize=512
Type=Scalable

[scalable/places]
Size=344
MinSize=16
MaxSize=512
Type=Scalable

[scalable/status]
Size=344
MinSize=16
MaxSize=512
Type=Scalable
