"""
Nebula Setup — System Configuration Backend
Handles squashfs unpacking, locale, users, bootloader, themes, and cleanup.
"""

import os
import re
import shutil
import subprocess
import textwrap
from typing import Callable, Optional

from backend.disk import get_uuid, is_efi_system


ProgressCB = Optional[Callable[[str], None]]


def _run(cmd: list, **kwargs) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, check=True, capture_output=True, text=True, **kwargs)


def _chroot(mount_root: str, cmd: list, env: dict = None, **kwargs):
    full_cmd = ["chroot", mount_root] + cmd
    env_kw = {}
    if env:
        base = os.environ.copy()
        base.update(env)
        env_kw["env"] = base
    return subprocess.run(full_cmd, check=True, capture_output=True, text=True,
                          **env_kw, **kwargs)


# ──────────────────────────────────────────────────────────────────────────────
# Unpack squashfs
# ──────────────────────────────────────────────────────────────────────────────

def unpack_squashfs(mount_root: str, squashfs_path: str, progress_cb: ProgressCB = None):
    """Unpack squashfs filesystem into mount_root."""
    if progress_cb:
        progress_cb("Unpacking filesystem…")

    # Clean any temporary contents in mount_root if needed (skip lost+found and boot)
    try:
        for item in os.listdir(mount_root):
            if item in ["lost+found", "boot"]:
                continue
            item_path = os.path.join(mount_root, item)
            if os.path.isdir(item_path) and not os.path.islink(item_path):
                shutil.rmtree(item_path, ignore_errors=True)
            else:
                try:
                    os.remove(item_path)
                except Exception:
                    pass
    except Exception:
        pass

    # Fallback squashfs paths
    import glob
    sources = [
        squashfs_path,
        "/cdrom/live/filesystem.squashfs",
        "/run/live/medium/live/filesystem.squashfs",
        "/lib/live/mount/medium/live/filesystem.squashfs",
        "/run/live/rootfs/filesystem.squashfs",
    ]
    sources += glob.glob("/run/live/**/filesystem.squashfs", recursive=True)
    sources += glob.glob("/lib/live/**/filesystem.squashfs", recursive=True)
    sources += glob.glob("/cdrom/**/filesystem.squashfs", recursive=True)

    actual_source = None
    for s in sources:
        if s and os.path.isfile(s):
            actual_source = s
            break

    if not actual_source:
        raise FileNotFoundError(f"squashfs not found at any expected path: {sources}")

    subprocess.run(
        ["unsquashfs", "-f", "-d", mount_root, actual_source],
        check=True
    )


# ──────────────────────────────────────────────────────────────────────────────
# Virtual filesystems (for chroot operations)
# ──────────────────────────────────────────────────────────────────────────────

def bind_vfs(mount_root: str):
    for fs, src, ftype in [
        ("/dev", "/dev", None),
        ("/dev/pts", "/dev/pts", None),
        ("/proc", None, "proc"),
        ("/sys", None, "sysfs"),
    ]:
        target = mount_root + fs
        os.makedirs(target, exist_ok=True)
        if src:
            subprocess.run(["mount", "--bind", src, target],
                           check=True, capture_output=True)
        else:
            subprocess.run(["mount", "-t", ftype, ftype, target],
                           check=True, capture_output=True)

    # Bind efivarfs if booted in UEFI mode
    efivars_host = "/sys/firmware/efi/efivars"
    if os.path.isdir(efivars_host):
        target = os.path.join(mount_root, "sys/firmware/efi/efivars")
        os.makedirs(target, exist_ok=True)
        subprocess.run(["mount", "--bind", efivars_host, target], capture_output=True)


def unbind_vfs(mount_root: str):
    for fs in [
        "/sys/firmware/efi/efivars",
        "/boot/efi",
        "/dev/pts",
        "/dev",
        "/proc",
        "/sys",
    ]:
        target = mount_root + fs
        subprocess.run(["umount", "-lf", target], capture_output=True)


# ──────────────────────────────────────────────────────────────────────────────
# fstab
# ──────────────────────────────────────────────────────────────────────────────

def setup_fstab(mount_root: str, root_part: str, efi_part: Optional[str],
                progress_cb: ProgressCB = None):
    if progress_cb:
        progress_cb("Configuring filesystems table…")

    root_uuid = get_uuid(root_part)
    lines = ["# /etc/fstab — generated by Nebula Setup\n"]

    if root_uuid:
        lines.append(f"UUID={root_uuid}\t/\text4\terrors=remount-ro\t0\t1\n")
    else:
        lines.append(f"{root_part}\t/\text4\terrors=remount-ro\t0\t1\n")

    if efi_part:
        efi_uuid = get_uuid(efi_part)
        if efi_uuid:
            lines.append(f"UUID={efi_uuid}\t/boot/efi\tvfat\tumask=0077\t0\t1\n")
        else:
            lines.append(f"{efi_part}\t/boot/efi\tvfat\tumask=0077\t0\t1\n")

    lines.append("tmpfs\t/tmp\ttmpfs\tnosuid,nodev\t0\t0\n")

    fstab_path = os.path.join(mount_root, "etc", "fstab")
    with open(fstab_path, "w") as f:
        f.writelines(lines)


# ──────────────────────────────────────────────────────────────────────────────
# Locale & timezone
# ──────────────────────────────────────────────────────────────────────────────

def setup_locale(mount_root: str, language: str, timezone: str,
                 keyboard_layout: str, keyboard_model: str,
                 progress_cb: ProgressCB = None):
    if progress_cb:
        progress_cb("Setting locale and timezone…")

    # locale.gen
    locale_gen = os.path.join(mount_root, "etc", "locale.gen")
    with open(locale_gen, "w") as f:
        f.write(f"{language}.UTF-8 UTF-8\n")
        if not language.startswith("en_US"):
            f.write("en_US.UTF-8 UTF-8\n")

    try:
        _chroot(mount_root, ["locale-gen"])
    except Exception:
        pass

    # /etc/locale.conf
    locale_conf = os.path.join(mount_root, "etc", "locale.conf")
    with open(locale_conf, "w") as f:
        f.write(f"LANG={language}.UTF-8\nLC_ALL={language}.UTF-8\n")

    # Default locale
    default_locale = os.path.join(mount_root, "etc", "default", "locale")
    with open(default_locale, "w") as f:
        f.write(f'LANG="{language}.UTF-8"\n')

    # Timezone via symlink
    tz_src = os.path.join(mount_root, "usr", "share", "zoneinfo", timezone)
    tz_dest = os.path.join(mount_root, "etc", "localtime")
    if os.path.exists(tz_src):
        if os.path.exists(tz_dest) or os.path.islink(tz_dest):
            os.remove(tz_dest)
        os.symlink(f"/usr/share/zoneinfo/{timezone}", tz_dest)

    # /etc/timezone
    tz_file = os.path.join(mount_root, "etc", "timezone")
    with open(tz_file, "w") as f:
        f.write(timezone + "\n")

    # Keyboard
    keyboard_conf = os.path.join(mount_root, "etc", "default", "keyboard")
    with open(keyboard_conf, "w") as f:
        f.write(textwrap.dedent(f"""
            XKBMODEL="{keyboard_model}"
            XKBLAYOUT="{keyboard_layout}"
            XKBVARIANT=""
            XKBOPTIONS=""
            BACKSPACE="guess"
        """).strip() + "\n")


def apply_live_keyboard_layout(keyboard_layout: str, keyboard_model: str = "pc105"):
    """
    Applies the keyboard layout immediately to the live running system/desktop session.
    Updates GNOME input-sources, setxkbmap, localectl, and /etc/default/keyboard.
    """
    try:
        from gi.repository import Gio, GLib
        settings = Gio.Settings.new("org.gnome.desktop.input-sources")
        builder = GLib.VariantBuilder.new(GLib.VariantType.new("a(ss)"))
        builder.add_value(GLib.Variant("(ss)", ("xkb", keyboard_layout)))
        settings.set_value("sources", builder.end())
        settings.apply()
    except Exception:
        pass

    # Update GSettings for the live session user via subprocess/dbus if running under sudo/pkexec
    for u in [os.environ.get("SUDO_USER"), "nebula"]:
        if not u:
            continue
        try:
            cmd = f'gsettings set org.gnome.desktop.input-sources sources "[(\\\'xkb\\\', \\\'{keyboard_layout}\\\')]"'
            subprocess.run(["su", "-", u, "-c", cmd], capture_output=True, timeout=2)
        except Exception:
            pass

    # setxkbmap for X11 / Xwayland
    try:
        subprocess.run(["setxkbmap", "-layout", keyboard_layout, "-model", keyboard_model], capture_output=True, timeout=2)
    except Exception:
        pass

    # localectl for systemd
    try:
        subprocess.run(["localectl", "set-x11-keymap", keyboard_layout, keyboard_model], capture_output=True, timeout=2)
        subprocess.run(["localectl", "set-keymap", keyboard_layout], capture_output=True, timeout=2)
    except Exception:
        pass

    # Live /etc/default/keyboard
    try:
        with open("/etc/default/keyboard", "w") as f:
            f.write(textwrap.dedent(f"""
                XKBMODEL="{keyboard_model}"
                XKBLAYOUT="{keyboard_layout}"
                XKBVARIANT=""
                XKBOPTIONS=""
                BACKSPACE="guess"
            """).strip() + "\n")
        subprocess.run(["udevadm", "trigger", "--subsystem-match=input", "--action=change"], capture_output=True, timeout=2)
    except Exception:
        pass


def apply_live_timezone(timezone: str):
    """
    Applies timezone immediately to the live system clock.
    """
    try:
        subprocess.run(["timedatectl", "set-timezone", timezone], capture_output=True, timeout=2)
        tz_src = f"/usr/share/zoneinfo/{timezone}"
        if os.path.exists(tz_src):
            if os.path.exists("/etc/localtime") or os.path.islink("/etc/localtime"):
                try: os.remove("/etc/localtime")
                except Exception: pass
            try: os.symlink(tz_src, "/etc/localtime")
            except Exception: pass
    except Exception:
        pass


def apply_live_theme(color_scheme: str):
    """
    Applies theme (prefer-dark / prefer-light) immediately to the live session and installer UI.
    """
    try:
        from gi.repository import Gio, Adw
        style_mgr = Adw.StyleManager.get_default()
        if color_scheme == "prefer-dark":
            style_mgr.set_color_scheme(Adw.ColorScheme.PREFER_DARK)
        else:
            style_mgr.set_color_scheme(Adw.ColorScheme.PREFER_LIGHT)

        settings = Gio.Settings.new("org.gnome.desktop.interface")
        settings.set_string("color-scheme", color_scheme)
        settings.apply()
    except Exception:
        pass



# ──────────────────────────────────────────────────────────────────────────────
# Hostname & machine-id
# ──────────────────────────────────────────────────────────────────────────────

def setup_hostname(mount_root: str, hostname: str, progress_cb: ProgressCB = None):
    if progress_cb:
        progress_cb("Configuring hostname…")

    with open(os.path.join(mount_root, "etc", "hostname"), "w") as f:
        f.write(hostname + "\n")

    hosts = os.path.join(mount_root, "etc", "hosts")
    with open(hosts, "w") as f:
        f.write(textwrap.dedent(f"""
            127.0.0.1    localhost
            127.0.1.1    {hostname}
            ::1          localhost ip6-localhost ip6-loopback
            ff02::1      ip6-allnodes
            ff02::2      ip6-allrouters
        """).strip() + "\n")

    # Generate fresh machine-id
    try:
        _chroot(mount_root, ["systemd-machine-id-setup"])
    except Exception:
        pass


# ──────────────────────────────────────────────────────────────────────────────
# User creation
# ──────────────────────────────────────────────────────────────────────────────

def create_user(mount_root: str, username: str, full_name: str, password: str,
                avatar_url: Optional[str] = None, progress_cb: ProgressCB = None):
    if progress_cb:
        progress_cb(f"Creating user '{username}'…")

    # Remove live user 'nebula' if chosen username is different
    if username != "nebula":
        try:
            _chroot(mount_root, ["userdel", "-r", "-f", "nebula"])
        except Exception:
            pass
        live_home = os.path.join(mount_root, "home", "nebula")
        shutil.rmtree(live_home, ignore_errors=True)

    # Check if user already exists
    user_exists = False
    try:
        _chroot(mount_root, ["id", username])
        user_exists = True
    except Exception:
        user_exists = False

    if not user_exists:
        _chroot(mount_root, [
            "useradd",
            "-m", "-s", "/bin/bash",
            "-c", full_name,
            username
        ])

    # Add to administrative, hardware, and desktop groups
    for grp in ["sudo", "audio", "video", "plugdev", "netdev", "bluetooth", "adm", "dialout", "cdrom", "dip", "users"]:
        try:
            _chroot(mount_root, ["usermod", "-aG", grp, username])
        except Exception:
            pass

    # Set password
    passwd_proc = subprocess.Popen(
        ["chroot", mount_root, "chpasswd"],
        stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE
    )
    passwd_proc.communicate(input=f"{username}:{password}\n".encode())

    # AccountsService profile — configure BOTH Session=gnome (Wayland) and XSession=gnome (X11)
    accounts_dir = os.path.join(mount_root, "var", "lib", "AccountsService", "users")
    os.makedirs(accounts_dir, exist_ok=True)
    account_file = os.path.join(accounts_dir, username)
    with open(account_file, "w") as f:
        f.write(textwrap.dedent(f"""
            [User]
            Language=
            Session=gnome
            XSession=gnome
            SystemAccount=false
            Icon=/home/{username}/.face
        """).strip() + "\n")

    # Copy DefaultUser avatar
    default_face_src = "/usr/share/pixmaps/faces/default.png"
    if not os.path.exists(os.path.join(mount_root, default_face_src.lstrip("/"))):
        default_face_src = None

    user_home = os.path.join(mount_root, "home", username)
    face_dest = os.path.join(user_home, ".face")
    if default_face_src and os.path.exists(os.path.join(mount_root, default_face_src.lstrip("/"))):
        shutil.copy(os.path.join(mount_root, default_face_src.lstrip("/")), face_dest)

    # If avatar URL provided, try to download it
    if avatar_url:
        try:
            import urllib.request
            urllib.request.urlretrieve(avatar_url, face_dest)
        except Exception:
            pass

    # Set AccountsService avatar
    icon_dest = os.path.join(mount_root, "var", "lib", "AccountsService", "icons", username)
    if os.path.exists(face_dest):
        shutil.copy(face_dest, icon_dest)

    # Update AccountsService icon reference
    with open(account_file, "w") as f:
        f.write(textwrap.dedent(f"""
            [User]
            Language=
            Session=gnome
            XSession=gnome
            SystemAccount=false
            Icon=/var/lib/AccountsService/icons/{username}
        """).strip() + "\n")

    # Critical security permissions: AccountsService refuses to read directory if not 0700
    try:
        _chroot(mount_root, ["chown", "-R", "root:root", "/var/lib/AccountsService"])
        _chroot(mount_root, ["chmod", "700", "/var/lib/AccountsService/users"])
        _chroot(mount_root, ["chmod", "600", f"/var/lib/AccountsService/users/{username}"])
    except Exception:
        pass

    # Ensure ~/.dmrc session fallback
    try:
        user_dmrc = os.path.join(user_home, ".dmrc")
        with open(user_dmrc, "w") as f:
            f.write("[Desktop]\nSession=gnome\n")
    except Exception:
        pass

    # Fix ownership and permissions of entire user home
    try:
        uid_gid = subprocess.check_output(
            ["chroot", mount_root, "id", "-u", username], text=True
        ).strip()
        subprocess.run(["chown", "-R", f"{uid_gid}:{uid_gid}", user_home],
                       capture_output=True)
        subprocess.run(["chmod", "700", user_home], capture_output=True)
        subprocess.run(["chmod", "-R", "u+rwX", user_home], capture_output=True)
        subprocess.run(["chmod", "644", os.path.join(user_home, ".dmrc")], capture_output=True)
    except Exception:
        pass


# ──────────────────────────────────────────────────────────────────────────────
# Theme
# ──────────────────────────────────────────────────────────────────────────────

def set_theme(mount_root: str, color_scheme: str, username: str,
              progress_cb: ProgressCB = None):
    if progress_cb:
        progress_cb("Applying theme preferences…")

    # Update gschema override
    override_path = os.path.join(mount_root, "usr/share/glib-2.0/schemas/99_nebulaos.gschema.override")
    if os.path.exists(override_path):
        with open(override_path, "r") as f:
            content = f.read()
        content = re.sub(
            r"color-scheme='[^']*'",
            f"color-scheme='{color_scheme}'",
            content
        )
        with open(override_path, "w") as f:
            f.write(content)

    try:
        _chroot(mount_root, ["glib-compile-schemas", "/usr/share/glib-2.0/schemas"])
    except Exception:
        pass

    # User dconf overrides
    user_home = os.path.join(mount_root, "home", username)
    dconf_dir = os.path.join(user_home, ".config", "dconf")
    os.makedirs(dconf_dir, exist_ok=True)


# ──────────────────────────────────────────────────────────────────────────────
# Bootloader
# ──────────────────────────────────────────────────────────────────────────────

def install_bootloader(mount_root: str, device: str, use_efi: bool,
                       install_mode: str = "erase",
                       progress_cb: ProgressCB = None):
    if progress_cb:
        progress_cb("Installing bootloader…")

    env = {"DEBIAN_FRONTEND": "noninteractive"}

    # Ensure os-prober is enabled in /etc/default/grub for detecting other OSes
    grub_default = os.path.join(mount_root, "etc/default/grub")
    if os.path.exists(grub_default):
        with open(grub_default, "r") as f:
            content = f.read()
        if "GRUB_DISABLE_OS_PROBER=" in content:
            content = re.sub(r"GRUB_DISABLE_OS_PROBER=.*", "GRUB_DISABLE_OS_PROBER=false", content)
        else:
            content += "\nGRUB_DISABLE_OS_PROBER=false\n"

        if install_mode == "dualboot":
            content = re.sub(r"GRUB_TIMEOUT=.*", "GRUB_TIMEOUT=5", content)
            content = re.sub(r"GRUB_TIMEOUT_STYLE=.*", "GRUB_TIMEOUT_STYLE=menu", content)

        with open(grub_default, "w") as f:
            f.write(content)

    # In dualboot mode, make sure silent snippet doesn't suppress the GRUB menu
    silent_cfg = os.path.join(mount_root, "etc/default/grub.d/00_nebula_silent.cfg")
    if install_mode == "dualboot" and os.path.exists(silent_cfg):
        try:
            with open(silent_cfg, "w") as f:
                f.write("GRUB_TIMEOUT=5\nGRUB_TIMEOUT_STYLE=menu\nGRUB_DISABLE_OS_PROBER=false\n")
        except Exception:
            pass

    if use_efi:
        try:
            _chroot(mount_root,
                    ["apt-get", "install", "-y", "--no-install-recommends",
                     "grub-efi-amd64", "efibootmgr"],
                    env=env)
        except Exception:
            pass

        # Standard UEFI GRUB install to /boot/efi
        _chroot(mount_root, [
            "grub-install",
            "--target=x86_64-efi",
            "--efi-directory=/boot/efi",
            "--bootloader-id=NebulaOS",
            "--recheck"
        ])

        # Also install fallback removable EFI binary (/boot/efi/EFI/BOOT/BOOTX64.EFI)
        try:
            _chroot(mount_root, [
                "grub-install",
                "--target=x86_64-efi",
                "--efi-directory=/boot/efi",
                "--bootloader-id=NebulaOS",
                "--recheck",
                "--removable"
            ])
        except Exception:
            pass
    else:
        try:
            _chroot(mount_root,
                    ["apt-get", "install", "-y", "--no-install-recommends", "grub-pc"],
                    env=env)
        except Exception:
            pass

        _chroot(mount_root, [
            "grub-install",
            "--target=i386-pc",
            "--recheck",
            device
        ])

    if progress_cb:
        progress_cb("Detecting operating systems & generating bootloader configuration…")
    _chroot(mount_root, ["update-grub"])


# ──────────────────────────────────────────────────────────────────────────────
# Initramfs
# ──────────────────────────────────────────────────────────────────────────────

def update_initramfs(mount_root: str, progress_cb: ProgressCB = None):
    if progress_cb:
        progress_cb("Updating initramfs…")
    try:
        _chroot(mount_root, ["update-initramfs", "-u", "-k", "all"])
    except Exception:
        pass


# ──────────────────────────────────────────────────────────────────────────────
# Post-install cleanup
# ──────────────────────────────────────────────────────────────────────────────

def post_cleanup(mount_root: str, username: str, install_mode: str = "erase",
                 progress_cb: ProgressCB = None):
    if progress_cb:
        progress_cb("Running post-install cleanup…")

    cleanup_script = os.path.join(mount_root, "usr/lib/nebulaos/post-install-cleanup.sh")
    if os.path.exists(cleanup_script):
        try:
            _chroot(mount_root, ["/usr/lib/nebulaos/post-install-cleanup.sh", username, install_mode])
        except Exception:
            pass

    # Completely remove installer, setup files, and autostarts from target system
    for path in [
        os.path.join(mount_root, "usr/bin/nebula-setup"),
        os.path.join(mount_root, "usr/bin/install-nebula"),
        os.path.join(mount_root, "usr/bin/nebula-installer"),
        os.path.join(mount_root, "usr/bin/nebula-session-init"),
        os.path.join(mount_root, "usr/share/nebula-setup"),
        os.path.join(mount_root, "usr/share/applications/installer.desktop"),
        os.path.join(mount_root, "usr/share/applications/install-nebula.desktop"),
        os.path.join(mount_root, "usr/share/applications/nebula-installer-autostart.desktop"),
        os.path.join(mount_root, "usr/share/applications/calamares.desktop"),
        os.path.join(mount_root, "usr/share/applications/install-debian.desktop"),
        os.path.join(mount_root, "etc/xdg/autostart/nebula-installer-autostart.desktop"),
        os.path.join(mount_root, "etc/xdg/autostart/calamares.desktop"),
        os.path.join(mount_root, "etc/xdg/autostart/calamares-desktop-icon.desktop"),
        os.path.join(mount_root, "home", username, "Desktop/installer.desktop"),
        os.path.join(mount_root, "home", username, "Desktop/install-nebula.desktop"),
        os.path.join(mount_root, "etc/skel/Desktop/installer.desktop"),
        os.path.join(mount_root, "etc/skel/Desktop/install-nebula.desktop"),
    ]:
        try:
            if os.path.isdir(path) and not os.path.islink(path):
                shutil.rmtree(path, ignore_errors=True)
            elif os.path.exists(path):
                os.remove(path)
        except Exception:
            pass

    # Enable NetworkManager
    try:
        _chroot(mount_root, ["systemctl", "enable", "NetworkManager"])
    except Exception:
        pass

    # Configure GDM3 daemon.conf on installed system: Wayland enabled, clean login prompt, strictly default to GNOME
    gdm_dir = os.path.join(mount_root, "etc", "gdm3")
    os.makedirs(gdm_dir, exist_ok=True)
    gdm_conf = os.path.join(gdm_dir, "daemon.conf")
    try:
        with open(gdm_conf, "w") as f:
            f.write(textwrap.dedent("""
                [daemon]
                AutomaticLoginEnable = false
                WaylandEnable = true
                DefaultSession = gnome.desktop

                [security]

                [xdmcp]

                [chooser]

                [debug]
            """).strip() + "\n")
        os.chmod(gdm_conf, 0o644)
    except Exception:
        pass

    # Ensure GDM PreSession script guarantees Session=gnome for all users
    try:
        presession_dir = os.path.join(mount_root, "etc", "gdm3", "PreSession")
        os.makedirs(presession_dir, exist_ok=True)
        presession_file = os.path.join(presession_dir, "Default")
        hook = (
            '\nif [ -n "$USER" ] && [ -f "/var/lib/AccountsService/users/$USER" ]; then\n'
            '    sed -i "s|^Session=.*|Session=gnome|" "/var/lib/AccountsService/users/$USER" 2>/dev/null || true\n'
            'fi\n'
        )
        if os.path.exists(presession_file):
            with open(presession_file, "r") as f:
                content = f.read()
            if "Session=gnome" not in content:
                with open(presession_file, "a") as f:
                    f.write(hook)
        else:
            with open(presession_file, "w") as f:
                f.write("#!/bin/sh\n" + hook + "exit 0\n")
            os.chmod(presession_file, 0o755)
    except Exception:
        pass

    # Ensure /home/{username} is completely owned by user with correct permissions
    user_home = os.path.join(mount_root, "home", username)

    if os.path.isdir(user_home):
        try:
            _chroot(mount_root, ["chown", "-R", f"{username}:{username}", f"/home/{username}"])
            _chroot(mount_root, ["chmod", "700", f"/home/{username}"])
            _chroot(mount_root, ["chmod", "-R", "u+rwX", f"/home/{username}"])
        except Exception:
            pass

    # Update desktop DB so installer disappears from the app list
    try:
        _chroot(mount_root, ["update-desktop-database", "/usr/share/applications"])
    except Exception:
        pass

    if progress_cb:
        progress_cb("Finalizing…")


# ──────────────────────────────────────────────────────────────────────────────
# Copy resolv.conf for network in chroot
# ──────────────────────────────────────────────────────────────────────────────

def setup_resolv(mount_root: str):
    src = "/etc/resolv.conf"
    dest = os.path.join(mount_root, "etc", "resolv.conf")
    try:
        if os.path.islink(dest):
            os.remove(dest)
        shutil.copy2(src, dest)
    except Exception:
        pass
